### ISSUE TITLE
Lightbox is not Working with Bootstrap

### ISSUE THREAD

**Issue by MuhaddiMu** [XiongAmao/vue-easy-lightbox#10]
I'm not sure why it's not working with Bootstrap. 

When I remove `import ('Bootstrap.css)` its working fine while my custom stylesheet still there. 

Any help would be much appreciated

Thanks

**Comment by GreenLeewayDesignCastle** [comment]
I have the same problem, using bootstrap 3.3.6

**Comment by GreenLeewayDesignCastle** [comment]
I fixed it by adding a class to the element and adding this class afterwards in te component like this : 
` <customer-upload-light-box
                :visible="visible"
                :imgs="image"
                @hide="hideImage"
                class="force-display"
        ></customer-upload-light-box>`
and like this : 
`<style lang="scss">
    .force-display{
        display:block!important;
    }
</style>`

The .vue component would look like : 

`<template>
    <div>
        <customer-upload-light-box
                :visible="visible"
                :imgs="image"
                @hide="hideImage"
                class="force-display"
        ></customer-upload-light-box>
        <customer-activities-bar></customer-activities-bar>
    </div>
</template>

<script>
    import LightBox from 'vue-easy-lightbox';

    export default {
        name: 'app',
        data() {
            return {
            }
        },
        methods: {
            hideImage: function()
            {
                this.$store.commit('HIDE_IMAGE', '');
            },
        },
        computed:{
            visible() {
                return this.$store.getters.visible;
            },
            image() {
                return this.$store.getters.image;
            },
        },
        components: {
            customerUploadLightBox: LightBox,
        }
    }
</script>

<style lang="scss">
    .force-display{
        display:block!important;
    }
</style>
`

**Comment by MuhaddiMu** [comment]
Thanks alot @GreenLeewayDesignCastle It's working now. 💯

**Comment by XiongAmao** [comment]
I didn't use Bootstrap. It's there any demos?
Should i add `display:block` to component's root element?
(I'm sorry for viewing issues too late

**Comment by MuhaddiMu** [comment]
Here's the simple project I am working on if you can take a look:
https://github.com/MuhaddiMu/VueGallery

**Comment by XiongAmao** [comment]
Thx guys ! @MuhaddiMu @GreenLeewayDesignCastle 
I fixed it https://github.com/XiongAmao/vue-easy-lightbox/commit/a6ec2458c66f53a3bf70cc470e5a48ad757c1381 & release 0.3.11
