### ISSUE TITLE
Cannot access css build

### ISSUE THREAD

**Issue by sheremet-va** [XiongAmao/vue-easy-lightbox#106]
Because `exports` now doesn't allow accessing `./dist` it's impossible to import CSP build.

Bug introduced in:

- https://github.com/XiongAmao/vue-easy-lightbox/commit/e39ad2952cf1034d48efb77b9c67ab96fa9254a8

Possible solution:

Add `./*` to exports:

```json
  "exports": {
    ".": {
      "import": "./dist/vue-easy-lightbox.esm.min.js",
      "require": "./dist/vue-easy-lightbox.common.min.js"
    },
    "./*": "./*"
  },
```
Or better add another entry point:

```json
  "exports": {
    ".": {
      "import": "./dist/vue-easy-lightbox.esm.min.js",
      "require": "./dist/vue-easy-lightbox.common.min.js"
    },
    "./external-css/js": {
      "import": "./dist/external-css/vue-easy-lightbox.esm.min.js",
      "require": "./dist/external-css/vue-easy-lightbox.common.min.js",
      "browser": "./dist/external-css/vue-easy-lightbox.umd.min.js"
    },
    "./external-css/css": "./dist/external-css/vue-easy-lightbox.css",
    "./*": "./*"
  },
```

**Comment by XiongAmao** [comment]
I did some tests and the `export conditional` only works with full path. 
So i only specify `vue-easy-lightbox/external` alias and other paths should work with `./*`. 

It was released in v1.8.2.

https://github.com/XiongAmao/vue-easy-lightbox/blob/9a32dd6e3d022f60dee31e9e4e79d5debe45b7a7/package.json#L17-L30

alias usage: 

```js
import VueEasyLightbox from 'vue-easy-lightbox/external-css'

// css
import 'vue-easy-lightbox/external-css/vue-easy-lightbox.css'
```
