### ISSUE TITLE
`oferflow-y:hidden` style is not removed on body element on browser back click

### ISSUE THREAD

**Issue by tsekka** [XiongAmao/vue-easy-lightbox#116]
### Steps to reproduce
1. For start, go to a longer page, such as https://onycat.com/vue-easy-lightbox/guide/ for example.
2. Navigate to page with demo lightbox (click on logo on top left)
3. Open lightbox (click on image)
4. Click browser's back button
5. Notice that you cannot scroll page anymore as the  `oferflow-y:hidden` is still on body element.

**Comment by XiongAmao** [comment]
The issue was fixed in v1.11.0.
