### ISSUE TITLE
请问vue2能用吗

### ISSUE THREAD

**Issue by 110sec** [XiongAmao/vue-easy-lightbox#118]

**Comment by XiongAmao** [comment]
v0.x是vue2的版本，与vue3版本api上有不同，
可以通过 `npm install vue-easy-lightbox@vue2` ，或者 `npm install vue-easy-lightbox@^0.20.0` 安装，
文档源码可以参考这里： https://github.com/XiongAmao/vue-easy-lightbox/tree/vue2.x
