### ISSUE TITLE
Both zoomDisabled and moveDisabled do not work, Move and Zoom are always enabled.

### ISSUE THREAD

**Issue by simpleport** [XiongAmao/vue-easy-lightbox#120]
Hi there,

This plugin is very cool, but I am running into some issues with it. 

With :zoomDisabled set to true and :moveDisabled set to true, I still am able to zoom and move the image. 

However, the :loop prop works exactly as expected, and I am able to set it to true to loop and false to turn looping off.

Check out my gist here to test for yourself: https://gist.github.com/simpleport/9a3a0468849439f2ee92f7c98ea9d3dd

**Comment by XiongAmao** [comment]
Hi, 

`vue-easy-lightbox` does not have `zoomDisabled` props. 

HTML tags and attribute names are case-insensitive ([docs here](https://vuejs.org//guide/essentials/component-basics.html#dom-template-parsing-caveats)), this is the correct usage: 

```html
 <vue-easy-lightbox :move-disabled="true"></vue-easy-lightbox>
```
