### ISSUE TITLE
Icons not showing up when the component used within a shadow root

### ISSUE THREAD

**Issue by RavishaHeshanE25** [XiongAmao/vue-easy-lightbox#121]
Hi, I'm trying to use the lightbox component within a shadow root for a chrome extension. but since the [iconfont.js](https://github.com/XiongAmao/vue-easy-lightbox/blob/main/src/assets/svg/iconfont.js) appends SVG icons into the body of the document icons are not available within the shadow root. It would be great if you could expose a prop to define the icon container element selector

**Comment by XiongAmao** [comment]
HI, 
I made SVG included in vue component. 

This may help you, you can try v1.12.0.

https://github.com/XiongAmao/vue-easy-lightbox/blob/09ee6944f55f3ed7f8afe51015c372a9f3ee89ee/src/vue-easy-lightbox.tsx#L672
https://github.com/XiongAmao/vue-easy-lightbox/blob/09ee6944f55f3ed7f8afe51015c372a9f3ee89ee/src/components/default-icons.tsx#L3-L77

**Comment by RavishaHeshanE25** [comment]
@XiongAmao Thanks for the quick fix. 1.12.0 fixed the issues so I'm closing this. Keep up the good work!
