### ISSUE TITLE
Disabled pinch on device

### ISSUE THREAD

**Issue by MIGUELGM98** [XiongAmao/vue-easy-lightbox#130]
How can I disable the pinch option when zooming on a real device, I have this problem when pinching
![image](https://user-images.githubusercontent.com/47856882/231570121-b4d2d966-916e-4f6a-a978-82915f2d262d.png)

**Comment by XiongAmao** [comment]
HI, there is no options to disable/enable pinch. I'll add this option later.
And can you provide some code for this problem, maybe i can fix it.

**Comment by XiongAmao** [comment]
Hi, i added  `pinchDisabled` prop in v1.16.0. 
Maybe it can help you to solve this issue.
