### ISSUE TITLE
Gallery always opens with index 0

### ISSUE THREAD

**Issue by MaxGietl** [XiongAmao/vue-easy-lightbox#133]
The index of the gallery is always set to 0, ignoring the index property

**Comment by XiongAmao** [comment]
Hi, sorry for the late reply.
The initialized index is actually in effect here:
https://github.com/XiongAmao/vue-easy-lightbox/blob/f7b2ce57a6102a2f3209ae2b221883ee54f8eabf/src/vue-easy-lightbox.tsx#L451-L475
When `vue-easy-lightbox` is displayed it always try to use current `props.index`, `imgIndex` is only used internally.
Can you provide a repo where this issue happens?

**Comment by MoJongleur** [comment]
@XiongAmao Index doesn't really work on initialization, but after it listening works
