### ISSUE TITLE
自定义按钮，被放大后的图片遮挡了，操作不对吗？

### ISSUE THREAD

**Issue by LindaPhillips820191** [XiongAmao/vue-easy-lightbox#138]

**Comment by XiongAmao** [comment]
Hi,
我不确定具体的问题是什么，你可以参考一下默认的样式，默认的toolbar 类名是`vel-toolbar`，按钮在这个toolbar下面，可以按你的需求自定义
https://github.com/XiongAmao/vue-easy-lightbox/blob/main/src/styles/toolbar.scss
