### ISSUE TITLE
Feature request - disable escaping for titles.

### ISSUE THREAD

**Issue by chryssalid** [XiongAmao/vue-easy-lightbox#139]
It would be great to use HTML in titles.

**Comment by XiongAmao** [comment]
Hi, you can use HTML in `v-slot:title`.
```vue
<vue-easy-lightbox>
  <template #title>
    <div class="vel-img-title">Test</div>
  </template>
</vue-easy-lightbox>
```

**Comment by chryssalid** [comment]
@XiongAmao  yes but does this allow me to use it for a group of images where every one has it's unique title?

**Comment by XiongAmao** [comment]
You can use this feature: https://vuejs.org/guide/components/slots.html#scoped-slots

Current image `{ src?: string, title?: string, alt?: string }` passed by slotProps.
These come from what you passed to prop `imgs`.

```vue
<template #title="{ currentImg }">
   <div class="vel-img-title">{{ currentImg?.title }}</div>
</template>
```

Source code: 

https://github.com/XiongAmao/vue-easy-lightbox/blob/69e4f42f34f4d470f16cb58dce51c3bf612d86d4/src/vue-easy-lightbox.tsx#L668-L672
