### ISSUE TITLE
How can we implement this with objects, instead of array?

### ISSUE THREAD

**Issue by SaadKhanMalik** [XiongAmao/vue-easy-lightbox#14]
Template: 

`
      <section class="page media-board">
        <div
          v-for="(images, index) in mediaWallImages"
          :key="index"
          :class="images.size"
          :style="{backgroundImage: `url(${images.img})` }"
          @click="() => showImg(index)"
        />
        <VueEasyLightbox
          :visible="visible"
          :imgs="images.img"???
          :index="index"
          @hide="handleHide"
        />
      </section>
`

Data:

`
mediaWallImages: [
        {
          id: 1,
          // img: require("@/assets/main/subscribe_bg.png"),
          img:
            "https://via.placeholder.com/1000x660/50575D/fff.png?text=1000x600|Media_Wall_01",
          title: "Customised Local Manufacturing",
          size: "nor"
        },
        {
          id: 2,
          img:
            "https://via.placeholder.com/1000x660/50575D/fff.png?text=1000x600|Media_Wall_02",
          title: "Customised Local Manufacturing",
          size: "tall"
        }
`

Method:

`
    showImg(index) {
      this.index = index;
      this.visible = true;
    },
    handleHide() {
      this.visible = false;
    }
`

**Comment by XiongAmao** [comment]
You can use `Array.prototype.map()` :
```js
export default {
  data() {
    return {
      mediaWallImages: [] // your array
    }
  },
  computed: {
    images () {
      return mediaWallImages.map(obj => {
        return obj.img
      })
    }
  }
}
```
