### ISSUE TITLE
missing param disableDoubleclick

### ISSUE THREAD

**Issue by scco** [XiongAmao/vue-easy-lightbox#142]
i do not know how to disable the "doubleclick" feature on a lightbox image.
this feature would just make sense, when :moveDisabled=false  :zoomDisabled=false

when move is disabled, and zoom is disabled, the doubleclick just lead into a weired 200% big image

i suggest to a ) add a param disableDoubleclick
or b) disable the doubleclick listener when zoom is disabled

any way to disable this doubleclick, without modify the plugin ?

**Comment by XiongAmao** [comment]
Hi, i added prop `dblclickDisabled` (default: `false`) in v1.17.0.

**Comment by scco** [comment]
@XiongAmao thanks a lot, works !
