### ISSUE TITLE
Nuxt3 build warning

### ISSUE THREAD

**Issue by gyxoBka** [XiongAmao/vue-easy-lightbox#145]
Hi!

Warning:

> (node:9052) [DEP0166] DeprecationWarning: Use of deprecated double slash resolving ".//index.json" for module request ".//index.json" matched to "./*" in the "exports" field module resolution of the package at D:\<project path>\node_modules\vue-easy-lightbox\package.json imported from D:\<project path>\node_modules\nitropack\node_modules.

Reproductuin:
Nuxt 3.9.3

`
npm run build
`

**Comment by XiongAmao** [comment]
This issue was fixed in v1.18.0.

**Comment by DbPtZn** [comment]
老哥知道这是啥原因导致的吗？我在 nuxt3 中依赖了 immer 和 @iconify 这两个包都会产生这个错误，但排查 package.json 并没有发现双斜线、尾斜线的问题😔
