### ISSUE TITLE
unexpected body overflow unlock

### ISSUE THREAD

**Issue by qoo1476** [XiongAmao/vue-easy-lightbox#147]
hi may i ask a one request?

i created my own modal Component with body scroll lock
(body="overflow: hidden" when it opens)

the problem is vue-easy-lightbox is in my Custom Modal Component and whenever i close it,
my body overflow hidden style is gone.

and i found out it's because of these lines

![image](https://github.com/XiongAmao/vue-easy-lightbox/assets/68536972/01f9e164-1193-460f-a959-953e5e61e6fa)

is it possible enableScrolling() only triggers when scroll-disabled is true?

something like this,

if(props.scrollDisabled) {
     enableScrolling()
}

thanks in advance.

**Comment by XiongAmao** [comment]
Hi, it was fixed in v1.19.0.
