### ISSUE TITLE
Add option to close model by pressing escape and ability to have a click handler on the image

### ISSUE THREAD

**Issue by jamesmorgan** [XiongAmao/vue-easy-lightbox#15]

**Comment by XiongAmao** [comment]
Hi, i think 'escape pressing' is a good idea. I will add keyboard feature later.
I guess you mean setting a close-btn on the image instead of the top right corner of the screen.
If you mean this, i will try to implement it.

**Comment by jamesmorgan** [comment]
yes - use case is that someone opens the image - then I would like to click again to close and or press the keybaord `escape` key to close, would love to see these added - thanks 🙏

**Comment by XiongAmao** [comment]
0.5.0 released, supports pressing esc to close modal.
Click handlers may cause conflicts in drag events, I haven’t figured out how to implement it.
Maybe later.. 😂

**Comment by jamesmorgan** [comment]
awesome - thankyou 🙏
