### ISSUE TITLE
Feature option: Background color and opacity

### ISSUE THREAD

**Issue by manukieli** [XiongAmao/vue-easy-lightbox#22]
Can you add new options like background color and opacity, and the posibilidad to show or not the toolbar??

Thank  you.

**Comment by XiongAmao** [comment]
You can hide toolbar like this
```html
<vue-easy-lightbox>
  <template slot="toolbar">
    <!-- empty it or customize it -->
  </template>
</vue-easy-lightbox>


<!-- vue@2.6.0+ -->
<vue-easy-lightbox>
  <template v-slot:toolbar>
    <!-- empty it or customize it -->
  </template>
</vue-easy-lightbox>
```

And you can rewrite class `.vel-modal`.
```css
.vel-modal {
  background-color: red !important; 
}
```
 It's a little bit ugly.. I will try to rewrite it to support custom styles. Maybe later ...😂
