### ISSUE TITLE
How can I handle onerror Img?

### ISSUE THREAD

**Issue by RexHung0302** [XiongAmao/vue-easy-lightbox#23]
I got Img from Api but I don't know the Img can correct show or can't.

How can I handle onerror Img ?

The issue like this : 
https://imgur.com/a/195ETZp

---

Thx EveryOne.

**Comment by XiongAmao** [comment]
It can't handle the error right now. I will add handler as soon as i can.

**Comment by RexHung0302** [comment]
@XiongAmao Thx You For your reply.

**Comment by XiongAmao** [comment]
@RexHung0302 
Hey, the error handler/placeholder and loading placeholder was released on v0.8.0.
Thank you for using this component.

**Comment by RexHung0302** [comment]
Ｗowwwwww~ thx you very muchhhhh!
It's really great.
