### ISSUE TITLE
Fix peerDependency

### ISSUE THREAD

**Issue by mkpaz** [XiongAmao/vue-easy-lightbox#29]
You're using `2.6.10` but your plugin is only compatible with `2.5.2`. 

```
vue-easy-lightbox@0.9.0 requires a peer of vue@2.5.22 but none is installed
```

**Comment by XiongAmao** [comment]
Yes. It may mislead users. I fixed it in v0.9.1 4d4d802d91bdce8e1f2ef53e6c8f4b812b640e73
