### ISSUE TITLE
Import images from local

### ISSUE THREAD

**Issue by metalsonic21** [XiongAmao/vue-easy-lightbox#30]
Hi, is there a way to import images locally instead of typing a link from the internet? I've tried the following and noone of these worked so I'm wondering if it's really possible or I must host the images online

` this.imgs = ["require(`../../assets/all-work/1.png`)", 'http://via.placeholder.com/350x150']`

` this.imgs = ['../../assets/all-work/1.png', 'http://via.placeholder.com/350x150']`

` this.imgs = ['@/assets/all-work/1.png', 'http://via.placeholder.com/350x150']`

**Comment by XiongAmao** [comment]
Hi, `vue-easy-lightbox` just receive a string or an array of strings of the image url , and the url of the image needs to be handled by webpack or comes from other address e.g. `http://via.placeholder.com/350x150`

I create a demo, you can check the detail [here](https://github.com/XiongAmao/vue-easy-lightbox/tree/master/demos/import-img-locally)
