### ISSUE TITLE
圖片拖拉效果

### ISSUE THREAD

**Issue by RexHung0302** [XiongAmao/vue-easy-lightbox#31]
先感謝作者提供這麼好的套件，上次提問的onerror圖片也有更新了，真的是非常非常感謝。

另外想請問目前支援手機拖拉圖片的功能了嗎？

看起來目前圖片僅能放大 但如果碰到比較長的圖片 放大後會無法往右或往左滑動看到詳細的圖片內容。

**Comment by XiongAmao** [comment]
Hi，非常感谢你使用这个组件，目前还不支持手机拖拽的功能，主要原因是我还没想好如何处理pc和mobile下缩放以及换页的逻辑，所以暂时还没实现相关的功能。大概这两周会做一个小版本看一下效果。

现在的放大缩小功能是放在页面底部的一个toolbar，我将放大/缩小/旋转/换页/关闭这些功能都通过vue 的[slot](https://github.com/XiongAmao/vue-easy-lightbox#use-vue-slot-custom-buttons-or-toolbar)提供了占位以及对应的调用方法，如果有需要的话，可以自定义你需要的工具栏或者按钮用于上述的功能。

**Comment by XiongAmao** [comment]
Hi, 我已经实现了手机拖拽和缩放的功能，发布在了v0.10.2，欢迎来试用。

**Comment by RexHung0302** [comment]
哇 感謝作者持續更新 真的很厲害 請收下我的膝蓋 辛苦了！！！
