### ISSUE TITLE
Remove the bottom buttons

### ISSUE THREAD

**Issue by RaulCorreia** [XiongAmao/vue-easy-lightbox#39]
How to remove the bottom buttons? and leave only those to move on to the next image?

**Comment by XiongAmao** [comment]
Hi,  you can use an empty element as `slot` to replace `toolbar`, which may be a bit ugly, but it works. Maybe it would be better to add a prop for hiding `toolbar`?
```vue
<vue-easy-lightbox
  :visible="visible"
  :imgs="imgs"
  @hide="handleHide"
>
  <div slot="toolbar"></div>

  <!-- or vue@2.6.0+ v-slot -->
  <div v-slot:toolbar></div>
</vue-easy-lightbox>
```

**Comment by RaulCorreia** [comment]
I think it interesting to have prop to change the template, giving the possibility to customize, I will test this alternative of an empty slot
