### ISSUE TITLE
Does not work on Firefox mobile

### ISSUE THREAD

**Issue by Matiyeu** [XiongAmao/vue-easy-lightbox#40]
The page change does not work on Firefox mobile

Tested with
Firefox : 68.7.0
Firefox Nightly : 77.0a1
vue-easy-lightbox : 0.10.3

**Comment by XiongAmao** [comment]
I tried the [`examples`](https://github.com/XiongAmao/vue-easy-lightbox/blob/master/examples/App.vue) page on firefox(68.7.0/Nightly: 77.0a1) with no problems.
Can you provide a demo?

**Comment by Matiyeu** [comment]
Yes https://www.escrime-occasion.com/annonces/sous-cuirasse-800n-gaucher-e269eab/

**Comment by XiongAmao** [comment]
It seems that the double click or text selection triggered when clicking on the next-button caused the zoom. And this page's `meta:viewport` does not have `maximum-scale, minimum-scale, and user-scalable`, so the page's viewport width and height become larger.

I added `user-select: none` to `button`/ `toolbar` / `img`, which should not trigger the double click event again. 

V0.12.0 is released, you shouldn't need to make other changes.

**Comment by Matiyeu** [comment]
Nope it doesn't work with v0.12.0 :confused:

**Comment by XiongAmao** [comment]
😅 Emm, when I tested it, firefox on the PC also reproduced the issue, which I thought could be fixed.
I'll try to figure out what's the problem with mobile firefox.

**Comment by XiongAmao** [comment]
Try v0.12.1.

**Comment by Matiyeu** [comment]
Thanks it works! 😉
