### ISSUE TITLE
d.ts for Vue.js 3.0 

### ISSUE THREAD

**Issue by XiongAmao** [XiongAmao/vue-easy-lightbox#53]
I customized the components's d.ts file in Vue.js 2.0.
In the current version,  the correct d.ts does not seem to be exported when using rollup-vue-plugin.
If anyone has experience with typescript , welcome PR.  😏😏

**Comment by AlexandreHiroyuki** [comment]
Hi. Recently, I started learning typescript with Vue 3. So I want to work on it.

**Comment by XiongAmao** [comment]
Vue.js 3 compatible d.ts is exported in v1.0.0-rc.3.
