### ISSUE TITLE
The picture is blurry.

### ISSUE THREAD

**Issue by k3341095** [XiongAmao/vue-easy-lightbox#54]
![image](https://user-images.githubusercontent.com/17330375/96949907-fa299580-1523-11eb-84f4-e7a4c39338fc.png)

The top image is an easy-lightbox image.
The image below is when the same picture is opened directly
This is the image you see.
Why does the image in the lightbox look blurry?
All sizes are 100%.

**Comment by k3341095** [comment]
![image](https://user-images.githubusercontent.com/17330375/96950461-517c3580-1525-11eb-941d-b5a8fdeaf24e.png)

The top image is a firefox lightbox capture.

I tested it on Firefox too
It works well in Firefox. cleanly
both lightbox and direct

Lightbox blur in chrome
Direct is clear

Both browsers are 100% scaled.

**Comment by k3341095** [comment]
![image](https://user-images.githubusercontent.com/17330375/96950662-c51e4280-1525-11eb-917d-dc537bda9842.png)

top chrome
bottom firefox

lightbox

**Comment by k3341095** [comment]
I found the reason.
css
vertical-align: middle ----> blur
![image](https://user-images.githubusercontent.com/17330375/96951064-aff5e380-1526-11eb-915f-2c18cc359846.png)

disable vertical-align ---> clean
![image](https://user-images.githubusercontent.com/17330375/96951082-b97f4b80-1526-11eb-91ab-1ae4d8d33d8c.png)

**Comment by XiongAmao** [comment]
Hmmm,  It's weird, maybe some css and `vertical-align: middle` together casing the blurry image.
I can't remember why I used this style. 😂 

Try disabling `<img />`  `vertical-align` and then set `display: block` (I was probably trying to align the outer div`.vel-img-wrapper`.), does this work?
