### ISSUE TITLE
VueEasyLightbox not defined

### ISSUE THREAD

**Issue by epartakakalam** [XiongAmao/vue-easy-lightbox#56]
I copy pasted the script example in a plain HTML and i have an error VueEasyLightbox not defined

**Comment by XiongAmao** [comment]
If you are using `vue-easy-lightbox` (0.x , for Vue2), the global variable is `vue-easy-lightbox`.
The `vue-easy-lightbox` (1.x , for Vue 3) global variable is `VueEasyLightbox`.

**Comment by epartakakalam** [comment]
Thanks

Αποκτήστε το Outlook για Android<https://aka.ms/ghei36>
________________________________
