### ISSUE TITLE
Object(…) is not a function

### ISSUE THREAD

**Issue by RexHung0302** [XiongAmao/vue-easy-lightbox#57]
Hello I got a problem when use **yarn add vue-easy-lightbox** to auto install and my version is `"vue-easy-lightbox": "^1.0.0-rc.1"` and use `import VueLazyload from 'vue-lazyload';` on main.js, it got a error that **Object(…) is not a function**, but when I use yarn add **vue-easy-lightbox@0.7.0** is work normally.

Final, I'd like to thx author to make this package. Star+100000

**Comment by XiongAmao** [comment]
`vue-easy-lightbox@1.x+` is only for `vue@3`, if you are using `vue@2`, please install `vue-easy-lightbox@0.14.0`

**Comment by RexHung0302** [comment]
@XiongAmao Oh, thx you.
