### ISSUE TITLE
Nuxt example doesn't work with "vue-easy-lightbox": "^1.0.0-rc.3"

### ISSUE THREAD

**Issue by suruaku** [XiongAmao/vue-easy-lightbox#60]
Nuxt example works with `"vue-easy-lightbox": "^0.11.0"`, but I get the following warnings(which breaks the plugin) with the version "vue-easy-lightbox": "^1.0.0-rc.3".
I noticed that for vue 2 and 3 there is different import in ~/plugins but both of them gave me these warnings and project did not load correctly (images unclickable).
You can reproduce this by updating nuxt demo's version to `"vue-easy-lightbox": "^1.0.0-rc.3"`

```
|  WARN  Compiled with 12 warnings
|  WARN  in ./node_modules/vue-easy-lightbox/dist/vue-easy-lightbox.es5.esm.min.js
| "export 'Transition' (imported as 's') was not found in 'vue'
|
|  WARN  in ./node_modules/vue-easy-lightbox/dist/vue-easy-lightbox.es5.esm.min.js
| "export 'createBlock' (imported as 'n') was not found in 'vue'
|
|  WARN  in ./node_modules/vue-easy-lightbox/dist/vue-easy-lightbox.es5.esm.min.js
| "export 'createCommentVNode' (imported as 'i') was not found in 'vue'
|
|  WARN  in ./node_modules/vue-easy-lightbox/dist/vue-easy-lightbox.es5.esm.min.js
| "export 'createTextVNode' (imported as 'u') was not found in 'vue'
|
|  WARN  in ./node_modules/vue-easy-lightbox/dist/vue-easy-lightbox.es5.esm.min.js
| "export 'createVNode' (imported as 'r') was not found in 'vue'
|
|  WARN  in ./node_modules/vue-easy-lightbox/dist/vue-easy-lightbox.es5.esm.min.js
| "export 'defineComponent' (imported as 't') was not found in 'vue'
|
|  WARN  in ./node_modules/vue-easy-lightbox/dist/vue-easy-lightbox.es5.esm.min.js
| "export 'openBlock' (imported as 'e') was not found in 'vue'
|
|  WARN  in ./node_modules/vue-easy-lightbox/dist/vue-easy-lightbox.es5.esm.min.js
| "export 'renderSlot' (imported as 'a') was not found in 'vue'
|
|  WARN  in ./node_modules/vue-easy-lightbox/dist/vue-easy-lightbox.es5.esm.min.js
| "export 'resolveComponent' (imported as 'o') was not found in 'vue'
|
|  WARN  in ./node_modules/vue-easy-lightbox/dist/vue-easy-lightbox.es5.esm.min.js
| "export 'toDisplayString' (imported as 'f') was not found in 'vue'
|
|  WARN  in ./node_modules/vue-easy-lightbox/dist/vue-easy-lightbox.es5.esm.min.js
| "export 'withCtx' (imported as 'l') was not found in 'vue'
|
|  WARN  in ./node_modules/vue-easy-lightbox/dist/vue-easy-lightbox.es5.esm.min.js
| "export 'withModifiers' (imported as 'c') was not found in 'vue'
```

_Originally posted by @suruaku in https://github.com/XiongAmao/vue-easy-lightbox/issues/38#issuecomment-755324555_

**Comment by XiongAmao** [comment]
Nuxt example is not updated to Vue3. I will update it later.

**Comment by XiongAmao** [comment]
Nuxt.js is not yet ready for Vue.js 3 (https://github.com/nuxt/nuxt.js/issues/5708). I will track it and update example when Nuxt.js 3 is released.
`vue-easy-lightbox@0.x`(or use this `vue-easy-lightbox@vue2`) is for Vue.js 2, you should install this version for now. Both versions have the same fucntionality.

**Comment by XiongAmao** [comment]
Nuxt v3 stable version will release in this year. [nuxt3 roadmap](https://v3.nuxtjs.org/community/roadmap)
It works with `Vue.js 3`, and you can use `vue-easy-lightbox@1.x`.

I have added demos for Nuxt3 [here](https://github.com/XiongAmao/vue-easy-lightbox/tree/main/demos/nuxt3-demo). 
Nuxt3 desn't need any special setup, just refer to the documentation.
