### ISSUE TITLE
Feature request: Support swipe

### ISSUE THREAD

**Issue by Kakyno** [XiongAmao/vue-easy-lightbox#63]
Feature request, please add support swipe left and right on touch devices. 

Thanks

**Comment by timvanuum** [comment]
In the source code I see some touch events it seems. 
Is this about to be implemented or is this something else? @XiongAmao 

https://github.com/XiongAmao/vue-easy-lightbox/blob/65e31b61784abb8aea65db01850eedc456262088/src/vue-easy-lightbox.tsx#L240

**Comment by XiongAmao** [comment]
These touch event handling code are used to implement zooming and dragging on mobile.
At first it was designed to be used on PC browsers. The prev/next button, used to switch images, is also available on mobile.

I haven't figured out how to do a good gesture interaction yet, so some better examples are welcome.
PR is also welcome!

**Comment by kevinsimard** [comment]
@Kakyno 
CC: @timvanuum 

I added a pull request to add swipe support.
https://github.com/XiongAmao/vue-easy-lightbox/pull/70

**Comment by XiongAmao** [comment]
Thanks to @kevinsimard for #70.

v1.2.0 is released, you can now switch images by swiping when `moveDisabled` is set to `true`.

**Comment by Kakyno** [comment]
You guys are awesome! Thank you
