### ISSUE TITLE
Loop prop for Vue 2.0

### ISSUE THREAD

**Issue by FrostMegaByte** [XiongAmao/vue-easy-lightbox#72]
I'd very much like the recently released `loop` prop to also work for Vue 2. I've currently built a "hack" by listening to keyboard keys whether it is left or right arrow to change the index, but it would be very much appreciated if the `loop` prop is also available for Vue 2.

**Comment by XiongAmao** [comment]
Hi, this feature was implemented in v0.16.0.

**Comment by FrostMegaByte** [comment]
Absolutely fantastic! Much appreciated
