### ISSUE TITLE
Toolbar Methods

### ISSUE THREAD

**Issue by Drabuna** [XiongAmao/vue-easy-lightbox#76]
Hi, in the documentation regarding custom toolbar you mention:

```
<template v-slot:toolbar="{ toolbarMethods }">
    <button @click="toolbarMethods.zoomIn">zoom in</button>
    <button @click="toolbarMethods.zoomOut">zoom out</button>
    <button @click="toolbarMethods.rotateLeft">Anticlockwise rotation</button>
    <button @click="toolbarMethods.rotateRight">clockwise rotation</button>
  </template>

```

The question that I'm having is, where should the `toolbarMethods`  come from?
Can I import the default implementation somehow, and just configure the visuals?
Can you provide an example of how this should be used?

**Comment by Drabuna** [comment]
Poke-poke

**Comment by SeyamMs** [comment]
I was playing around that it worked by using the function name directly without toolbarMethod. like this 

`<template v-slot:toolbar="{ zoomIn, zoomOut }">
  <button @click="zoomOut">zoom out</button>
  <button @click="zoomIn">zoom in</button>
</template>`

but the zoomIn did work I believe this in
vue-easy-lightbox/src/vue-easy-lightbox.tsx
between lines 510 and 511 zoomIn is missing, I am not sure I was not able to compile this typescript.

**Comment by XiongAmao** [comment]
Sorry for the late reply.

This is a bug. When I refactored `vue-easy-lightbox` from vue 2 to vue 3, the implementation of slot-props in `vue3 tsx` was different from in `vue 2`, so I got it wrong.

It was fixed in v1.2.3

https://github.com/XiongAmao/vue-easy-lightbox/blob/38a78e05f712cdc383d939739b1674b875767c4e/src/vue-easy-lightbox.tsx#L510-L525

**Comment by SeyamMs** [comment]
Thanks for your reply first of all,

Yes huge change in Vue 3 syntax and composition API.

may I ask for instructions to build the src directory? I never used typescript
finally is this updated at npm too?

**Comment by XiongAmao** [comment]
It's hard to say how to build a typescript vue project.
Maybe you can try creating vue 3 ts project with Vite.  [Vite Guide](https://vitejs.dev/guide/#scaffolding-your-first-vite-project).
And i would recommend going through the official documentation to learn how to use TypeScript. [TypeScript Docs](https://www.typescriptlang.org/docs/)

v1.2.3 has been released to npm.

```shell
npm install vue-easy-lightbox@next 
# or
npm install vue-easy-lightbox@^1.2.3
```

**Comment by globalexport** [comment]
Hi! 

Is it possible to execute the toolbar methods programatically from outside of the component? I cannot retrieve the toolbar by template reference. 

Thanks!

**Comment by globalexport** [comment]
Solved it by placing a custom component into the slot to grab the toolbar methods.
