### ISSUE TITLE
为啥我在拖动图片的时候图片自己会放大缩小是BUG么？

### ISSUE THREAD

**Issue by dzk8890284** [XiongAmao/vue-easy-lightbox#8]

**Comment by XiongAmao** [comment]
能否提供demo和使用的场景？
可能是外部样式影响了缩放的CSS属性

**Comment by dzk8890284** [comment]
谢谢你！你这么一说我突然意识到了，我因为设置了点击之前的图片宽高都是100%，影响到了放大之后的图片，所以出现了问题！

**Comment by XiongAmao** [comment]
可能是类名冲突的问题，之后会重写组件的CSS类名

**Comment by XiongAmao** [comment]
v0.4.1 已经发布，类名已经重写，应该不会有样式冲突的问题，如果还有欢迎反馈
