### ISSUE TITLE
Firefox: Dragging issues

### ISSUE THREAD

**Issue by globalexport** [XiongAmao/vue-easy-lightbox#81]
**Expected behavior**: smooth image dragging by pressing and holding the mouse button.  

**Observed behavior**:  clunky mouse cursor attachment to the underlying image. 

Dragging the image only proceeds after the small preview image appears. At this point, it is necessary to release the mouse button for the image to stick to the cursor. Pressing the mouse button again will stop the drag operation. Dragging is stopping immediately on the cursor leaving the image area. 

I have created a short clip testing the demo area. 
https://www.file.io/download/AHnhjNP7H3U9

Tested Firefox Version: v92.0
OS: MacOS Big Sur

Firefox on Linux and Windows are working a bit smoother, although they also show the same attachment behaviour.

**Comment by XiongAmao** [comment]
Fixed in v1.2.4.
