### ISSUE TITLE
RTL not work correctly

### ISSUE THREAD

**Issue by sajjad5221** [XiongAmao/vue-easy-lightbox#86]
Hi, I'm using this package with vue3 but I have a problem with something. When I click on the previous icon, the next image is displayed to me and vice versa.
This also happens for the key left and key right.

**Comment by XiongAmao** [comment]
Hi, can you provide a repo?

**Comment by sajjad5221** [comment]
Thanks for your response. I apologize for being late.
This is the sample code:
https://codesandbox.io/s/vue-easy-light-box-rtl-bug-mivpo

**Comment by XiongAmao** [comment]
I add props `rtl` to enable RTL in v1.3.0. Try this version, it may help you.

**Comment by XiongAmao** [comment]
Try this,  I'm not sure if this is what you need. 
https://codesandbox.io/s/vue-easy-light-box-rtl-bug-forked-ztb6ne?file=/src/App.vue 

```vue
<template>
  <vue-easy-lightbox
    ref="lightboxRef"
    rtl
  />
</template>
```

**Comment by sajjad5221** [comment]
Yes. It's worked. thank you.
