### ISSUE TITLE
Feature Request - Double click to enlarge, and pinch to zoom

### ISSUE THREAD

**Issue by theoreticalsampling** [XiongAmao/vue-easy-lightbox#88]
Hi,

I like this lightbox component a lot! But I am missing two features: 1) A doubleclick or doubletap on the current image should adjust the image to fill the screen or should zoom in all the way 2) Pinch to zoom on touch devices is currently not working.

Since the component does not expose the image-domelement, I can't find a way to implement this feature in my own project.

Kind regards

**Comment by XiongAmao** [comment]
HI,

Doubleclick to enlarge image was implemented in v1.4.1. 
`Pinch` has been implemented in past versions.  If it doesn't work correctly, please provide a repo. I'll take a look.
