### ISSUE TITLE
Feature request - Make it impossible to close except by pressing the x button.

### ISSUE THREAD

**Issue by tunagohan** [XiongAmao/vue-easy-lightbox#92]
## Description

If you click on the background of a photo, the LightBox will be closed.

I would be happy if these could be optionally controlled, as there are cases where the background is accidentally clicked on when rotating an image or using the toolbox, causing it to be closed.

This is the best plugin. Thanks for making it!

## Image

![貼り付けた画像_2022_04_01_19_26](https://user-images.githubusercontent.com/19791597/161246368-e50afa08-b4d5-4cf1-a7e4-d56414035e8f.png)

**Comment by XiongAmao** [comment]
This feature was released in v1.5.0 and v0.18.0.
I'm sorry that I can't maintain this project these days, this release is a bit late...
