### ISSUE TITLE
Feature request - Options for hiding buttons and adding zoomDisabled

### ISSUE THREAD

**Issue by svk-man** [XiongAmao/vue-easy-lightbox#93]
Hello! nice plugin. It would be great if options were added

hiding buttons
![image](https://user-images.githubusercontent.com/17108861/170968264-e9e840eb-ad9e-4f3c-a86c-144c3d680965.png)

zoomDisabled
![image](https://user-images.githubusercontent.com/17108861/170968455-b9c66d30-8a97-4b55-85d3-f8bd167ebb36.png)

**Comment by itpropro** [comment]
Have you tried using the slots to customize your toolbar? https://onycat.com/vue-easy-lightbox/guide/#custom-buttons-or-toolbar

**Comment by XiongAmao** [comment]
This feature was released in `v1.14.0` & `v0.23.0`.

**Comment by svk-man** [comment]
> Have you tried using the slots to customize your toolbar? https://onycat.com/vue-easy-lightbox/guide/#custom-buttons-or-toolbar

thx for link!

**Comment by svk-man** [comment]
> This feature was released in `v1.14.0` & `v0.23.0`.

great! thank you!
