### ISSUE TITLE
Composition API examples

### ISSUE THREAD

**Issue by itpropro** [XiongAmao/vue-easy-lightbox#98]
Thanks for writing this neat lightbox module!
As the composition API is the new default way to handle things from Vue 3 on and the current version is Vue 3 exclusive, there should be at least some additional examples for usage with composition api in the docs.
Maybe you could even provide some composables, e.g. `useEasyLightbox`.

**Comment by XiongAmao** [comment]
Thanks for the helpful suggestions!
I will update the documentation and examples later.

**Comment by XiongAmao** [comment]
Docs have been updated and `useEasyLightbox` is available in v1.7.0.
I'm not quite sure if this is useful.  If I have some new ideas, I'll keep updating.

**Comment by itpropro** [comment]
Thank you, works perfect :)
